import Config

# Configure your database
config :elixir_drops, ElixirDrops.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "elixir_drops_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :elixir_drops, ElixirDropsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "f6NOSLy3KXcIQy9jKD3Tq6uRAtgXx1kji5xtkbXNhsdo2jN1ypf10SWji8rCd01X",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:elixir_drops, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:elixir_drops, ~w(--watch)]}
  ]

aws_access_key_id =
  System.get_env("AWS_ACCESS_KEY_ID") ||
    raise """
    environment variable AWS_ACCESS_KEY_ID is missing.
    """

aws_bucket =
  System.get_env("BUCKET_NAME") ||
    raise """
    environment variable AWS_BUCKET_NAME is missing.
    """

aws_endpoint_url =
  System.get_env("AWS_ENDPOINT_URL_S3") ||
    raise """
    environment variable AWS_ENDPOINT_URL_S3 is missing.
    """

aws_region =
  System.get_env("AWS_REGION") ||
    raise """
    environment variable AWS_REGION is missing.
    """

aws_secret_access_key =
  System.get_env("AWS_SECRET_ACCESS_KEY") ||
    raise """
    environment variable AWS_SECRET_ACCESS_KEY is missing.
    """

fly_api_token =
  System.get_env("FLY_API_TOKEN") ||
    raise "environment variable FLY_API_TOKEN is missing."

flame_memory_mb = 2048

config :flame, FLAME.FlyBackend,
  env: %{
    "AWS_ACCESS_KEY_ID" => aws_access_key_id,
    "AWS_ENDPOINT_URL_S3" => aws_endpoint_url,
    "AWS_REGION" => aws_region,
    "AWS_SECRET_ACCESS_KEY" => aws_secret_access_key,
    "BUCKET_NAME" => aws_bucket
  },
  memory_mb: flame_memory_mb,
  token: fly_api_token

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :elixir_drops, ElixirDropsWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/elixir_drops_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :elixir_drops, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :ueberauth, Ueberauth.Strategy.Github.OAuth,
  client_id: System.get_env("GITHUB_CLIENT_ID"),
  client_secret: System.get_env("GITHUB_CLIENT_SECRET")

config :elixir_drops, :s3,
  debug_requests: true,
  access_key_id: System.get_env("AWS_ACCESS_KEY_ID"),
  bucket: System.get_env("BUCKET_NAME"),
  endpoint_url: System.get_env("AWS_ENDPOINT_URL_S3"),
  region: System.get_env("AWS_REGION"),
  secret_access_key: System.get_env("AWS_SECRET_ACCESS_KEY")

config :elixir_drops_wallaby,
  wallaby_auth: [
    username: "elixir_drops_wallaby",
    password: "l3AVAovk4B8g5Sbq"
  ]
